---
#
# Include the shared gitlab CI definitions
#
include:
  - project: 'enterprisemodules/gitlab_ci'
    file: 'gitlab-ci.yml'

mq92_demo_check:
  extends: .demo_check
  variables:
    server: ml-mq92
mq91_demo_check:
  extends: .demo_check
  variables:
    server: ml-mq91

# mq91sol_demo_check:
#   extends: .demo_check
#   variables:
#     server: ml-mq91sol
#   before_script:
#     - mkdir -p modules/software/files
#     - cp ~/software/Solaris/IBM_MQ_9.1_SOLARIS_X86-64.tar.gz modules/software/files
#     - cp ~/software/Solaris/puppet-agent@7.8.0,5.11-1.i386.p5p modules/software/files
#     - cp ~/software/Solaris/9.1.0-IBM-MQ-SolarisX64-FP0007.tar.Z modules/software/files
#     - cp ~/software/Solaris/9.1.0-IBM-MQ-SolarisX64-FP0008.tar.Z modules/software/files

mq90_demo_check:
  extends: .demo_check
  variables:
    server: ml-mq90
# mqwindows_demo_check:
#   extends: .demo_check
#   variables:
#     server: ml-mqwindows
#   before_script:
#     - mkdir -p modules/software/files
#     - cp ~/software/puppet-agent-6.4.2-x64.msi modules/software/files
#     - cp ~/software/IBM_MQ_9.1_WINDOWS_TRIAL.zip modules/software/files
