---
#
# Include the shared gitlab CI definitions
#
include:
  - project: 'enterprisemodules/gitlab_ci'
    file: 'gitlab-ci.yml'

mq01_demo_check:
  extends: .demo_check
  variables:
    server: ml-mq01
  before_script:
    - mkdir -p modules/software/files
    - cp ~/software/IBM_MQ_9.1.0.0_LINUX_X86-64.tar.gz modules/software/files

# mqwindows_demo_check:
#   extends: .demo_check
#   variables:
#     server: ml-mqwindows
#   before_script:
#     - mkdir -p modules/software/files
#     - cp ~/software/puppet-agent-6.4.2-x64.msi modules/software/files
#     - cp ~/software/IBM_MQ_9.1_WINDOWS_TRIAL.zip modules/software/files

    